--- #YAML:1.0
name:                RRDTool-OO
version:             0.19
abstract:            Object-oriented interface to RRDTool
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.31
distribution_type:   module
requires:     
    Log::Log4perl:                 0.40
    RRDs:                          0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Mike Schilli <m@perlmeister.com>
